//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitowebBE.Adintar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NovedadStr", Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/")]
    [System.SerializableAttribute()]
    public partial class NovedadStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_tipnovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nro_novField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_admField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_entField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_cueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_tipdomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_plaField;
        
        private int Nro_adicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CognitowebBE.Adintar.NovedadCampoStr[] ColCamposNovedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_tipnovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_estnovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_orinovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_estnovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_orinovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fechaestado_novField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cod_tipnov {
            get {
                return this.Cod_tipnovField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_tipnovField, value) != true)) {
                    this.Cod_tipnovField = value;
                    this.RaisePropertyChanged("Cod_tipnov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nro_nov {
            get {
                return this.Nro_novField;
            }
            set {
                if ((object.ReferenceEquals(this.Nro_novField, value) != true)) {
                    this.Nro_novField = value;
                    this.RaisePropertyChanged("Nro_nov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Codigo_adm {
            get {
                return this.Codigo_admField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_admField, value) != true)) {
                    this.Codigo_admField = value;
                    this.RaisePropertyChanged("Codigo_adm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Codigo_ent {
            get {
                return this.Codigo_entField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_entField, value) != true)) {
                    this.Codigo_entField = value;
                    this.RaisePropertyChanged("Codigo_ent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cod_cue {
            get {
                return this.Cod_cueField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_cueField, value) != true)) {
                    this.Cod_cueField = value;
                    this.RaisePropertyChanged("Cod_cue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Codigo_tipdom {
            get {
                return this.Codigo_tipdomField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_tipdomField, value) != true)) {
                    this.Codigo_tipdomField = value;
                    this.RaisePropertyChanged("Codigo_tipdom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Cod_pla {
            get {
                return this.Cod_plaField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_plaField, value) != true)) {
                    this.Cod_plaField = value;
                    this.RaisePropertyChanged("Cod_pla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Nro_adic {
            get {
                return this.Nro_adicField;
            }
            set {
                if ((this.Nro_adicField.Equals(value) != true)) {
                    this.Nro_adicField = value;
                    this.RaisePropertyChanged("Nro_adic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CognitowebBE.Adintar.NovedadCampoStr[] ColCamposNovedad {
            get {
                return this.ColCamposNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.ColCamposNovedadField, value) != true)) {
                    this.ColCamposNovedadField = value;
                    this.RaisePropertyChanged("ColCamposNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Desc_tipnov {
            get {
                return this.Desc_tipnovField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_tipnovField, value) != true)) {
                    this.Desc_tipnovField = value;
                    this.RaisePropertyChanged("Desc_tipnov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Desc_estnov {
            get {
                return this.Desc_estnovField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_estnovField, value) != true)) {
                    this.Desc_estnovField = value;
                    this.RaisePropertyChanged("Desc_estnov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Desc_orinov {
            get {
                return this.Desc_orinovField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_orinovField, value) != true)) {
                    this.Desc_orinovField = value;
                    this.RaisePropertyChanged("Desc_orinov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Cod_estnov {
            get {
                return this.Cod_estnovField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_estnovField, value) != true)) {
                    this.Cod_estnovField = value;
                    this.RaisePropertyChanged("Cod_estnov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Cod_orinov {
            get {
                return this.Cod_orinovField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_orinovField, value) != true)) {
                    this.Cod_orinovField = value;
                    this.RaisePropertyChanged("Cod_orinov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Fechaestado_nov {
            get {
                return this.Fechaestado_novField;
            }
            set {
                if ((object.ReferenceEquals(this.Fechaestado_novField, value) != true)) {
                    this.Fechaestado_novField = value;
                    this.RaisePropertyChanged("Fechaestado_nov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NovedadCampoStr", Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/")]
    [System.SerializableAttribute()]
    public partial class NovedadCampoStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor_anteriorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor_anterior {
            get {
                return this.Valor_anteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.Valor_anteriorField, value) != true)) {
                    this.Valor_anteriorField = value;
                    this.RaisePropertyChanged("Valor_anterior");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/", ConfigurationName="Adintar.ServiciosDispatcherWEBBcBaSoap")]
    public interface ServiciosDispatcherWEBBcBaSoap {
        
        // CODEGEN: Generating message contract since element name pOrigen from namespace http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/GrabarNovedad_Generi" +
            "co", ReplyAction="*")]
        CognitowebBE.Adintar.GrabarNovedad_GenericoResponse GrabarNovedad_Generico(CognitowebBE.Adintar.GrabarNovedad_GenericoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabarNovedad_GenericoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabarNovedad_Generico", Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/", Order=0)]
        public CognitowebBE.Adintar.GrabarNovedad_GenericoRequestBody Body;
        
        public GrabarNovedad_GenericoRequest() {
        }
        
        public GrabarNovedad_GenericoRequest(CognitowebBE.Adintar.GrabarNovedad_GenericoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/")]
    public partial class GrabarNovedad_GenericoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pNro_Interno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CognitowebBE.Adintar.NovedadStr pNovedad;
        
        public GrabarNovedad_GenericoRequestBody() {
        }
        
        public GrabarNovedad_GenericoRequestBody(string pOrigen, string pNro_Interno, CognitowebBE.Adintar.NovedadStr pNovedad) {
            this.pOrigen = pOrigen;
            this.pNro_Interno = pNro_Interno;
            this.pNovedad = pNovedad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabarNovedad_GenericoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabarNovedad_GenericoResponse", Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/", Order=0)]
        public CognitowebBE.Adintar.GrabarNovedad_GenericoResponseBody Body;
        
        public GrabarNovedad_GenericoResponse() {
        }
        
        public GrabarNovedad_GenericoResponse(CognitowebBE.Adintar.GrabarNovedad_GenericoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/AdintarWEBBcBa/ServiciosDispatcherWEBBcBa/")]
    public partial class GrabarNovedad_GenericoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GrabarNovedad_GenericoResult;
        
        public GrabarNovedad_GenericoResponseBody() {
        }
        
        public GrabarNovedad_GenericoResponseBody(string GrabarNovedad_GenericoResult) {
            this.GrabarNovedad_GenericoResult = GrabarNovedad_GenericoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiciosDispatcherWEBBcBaSoapChannel : CognitowebBE.Adintar.ServiciosDispatcherWEBBcBaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiciosDispatcherWEBBcBaSoapClient : System.ServiceModel.ClientBase<CognitowebBE.Adintar.ServiciosDispatcherWEBBcBaSoap>, CognitowebBE.Adintar.ServiciosDispatcherWEBBcBaSoap {
        
        public ServiciosDispatcherWEBBcBaSoapClient() {
        }
        
        public ServiciosDispatcherWEBBcBaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosDispatcherWEBBcBaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDispatcherWEBBcBaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDispatcherWEBBcBaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CognitowebBE.Adintar.GrabarNovedad_GenericoResponse CognitowebBE.Adintar.ServiciosDispatcherWEBBcBaSoap.GrabarNovedad_Generico(CognitowebBE.Adintar.GrabarNovedad_GenericoRequest request) {
            return base.Channel.GrabarNovedad_Generico(request);
        }
        
        public string GrabarNovedad_Generico(string pOrigen, string pNro_Interno, CognitowebBE.Adintar.NovedadStr pNovedad) {
            CognitowebBE.Adintar.GrabarNovedad_GenericoRequest inValue = new CognitowebBE.Adintar.GrabarNovedad_GenericoRequest();
            inValue.Body = new CognitowebBE.Adintar.GrabarNovedad_GenericoRequestBody();
            inValue.Body.pOrigen = pOrigen;
            inValue.Body.pNro_Interno = pNro_Interno;
            inValue.Body.pNovedad = pNovedad;
            CognitowebBE.Adintar.GrabarNovedad_GenericoResponse retVal = ((CognitowebBE.Adintar.ServiciosDispatcherWEBBcBaSoap)(this)).GrabarNovedad_Generico(inValue);
            return retVal.Body.GrabarNovedad_GenericoResult;
        }
    }
}
